/* Generated by zen0x — do not edit by hand */
@define-color accent_color             {{ semantic.accent }};
@define-color accent_bg_color          {{ semantic.elevated }};
@define-color accent_fg_color          {{ semantic.bg }};

@define-color destructive_color        {{ semantic.danger }};
@define-color destructive_bg_color     {{ semantic.close }};
@define-color destructive_fg_color     {{ semantic.bg }};

@define-color success_color            {{ semantic.success }};
@define-color success_bg_color         {{ semantic.success }};
@define-color success_fg_color         {{ semantic.bg }};

@define-color warning_color            {{ semantic.warning }};
@define-color warning_bg_color         {{ semantic.warning }};
@define-color warning_fg_color         {{ semantic.bg }};

@define-color error_color              {{ semantic.danger }};
@define-color error_bg_color           {{ semantic.close }};
@define-color error_fg_color           {{ semantic.bg }};

@define-color window_bg_color          {{ semantic.bg }};
@define-color window_fg_color          {{ semantic.fg }};

@define-color view_bg_color            {{ semantic.surface }};
@define-color view_fg_color            {{ semantic.fg }};

@define-color card_bg_color            {{ semantic.panel }};
@define-color card_fg_color            {{ semantic.fg }};
@define-color card_shade_color         rgba(0, 0, 0, 0.07);

@define-color dialog_bg_color          {{ semantic.panel }};
@define-color dialog_fg_color          {{ semantic.fg }};

@define-color popover_bg_color         {{ semantic.elevated }};
@define-color popover_fg_color         {{ semantic.fg }};

@define-color sidebar_bg_color         {{ semantic.panel }};
@define-color sidebar_fg_color         {{ semantic.muted }};

@define-color headerbar_bg_color       {{ semantic.panel_alt }};
@define-color headerbar_fg_color       {{ semantic.fg }};
@define-color headerbar_border_color   {{ semantic.border }};
@define-color headerbar_backdrop_color {{ semantic.panel }};
@define-color headerbar_shade_color    rgba(0, 0, 0, 0.07);

@define-color thumbnail_bg_color       {{ semantic.panel }};
@define-color thumbnail_fg_color       {{ semantic.fg }};

@define-color shade_color              rgba(0, 0, 0, 0.36);
@define-color scrollbar_outline_color  {{ semantic.border }};
