foreground #dfe4dc
background #101510
selection_foreground #101510
selection_background #97d5a5
url_color #97d5a5

# Normal colors (0-7)
color0  #0a0f0b
color1  #ffb4ab
color2  #97d5a5
color3  #b6ccb8
color4  #a2ced9
color5  #b2f1bf
color6  #d2e8d3
color7  #c1c9bf

# Bright colors (8-15)
color8  #8b938a
color9  #ffdad6
color10 #b2f1bf
color11 #d2e8d3
color12 #beeaf6
color13 #97d5a5
color14 #b6ccb8
color15 #dfe4dc

cursor            #97d5a5
cursor_text_color #101510
