# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13.0

foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #89b4fa
url_color #89b4fa

color0 #1e1e2e
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #94e2d5
color7 #bac2de
color8 #45475a
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #cdd6f4

cursor #cdd6f4
cursor_text_color #1e1e2e
cursor_shape block
cursor_shape_unfocused hollow
cursor_trail 1

detect_urls yes
show_hyperlink_targets no
underline_hyperlinks hover

hide_window_decorations yes

window_padding_width 8 14
single_window_margin_width 0

shell /bin/zsh
