foreground           {{ semantic.fg }}
background           {{ semantic.bg }}
selection_foreground {{ semantic.bg }}
selection_background {{ semantic.accent }}
url_color            {{ semantic.link }}
cursor               {{ semantic.fg }}
cursor_text_color    {{ semantic.bg }}

color0  {{ palette.black }}
color1  {{ palette.red_dark }}
color2  {{ palette.green_dark }}
color3  {{ palette.yellow_dark }}
color4  {{ palette.blue_dark }}
color5  {{ palette.purple_dark }}
color6  {{ palette.teal_dark }}
color7  {{ palette.grey_150 }}
color8  {{ palette.grey_350 }}
color9  {{ palette.red_light }}
color10 {{ palette.green_light }}
color11 {{ palette.yellow_light }}
color12 {{ palette.blue_light }}
color13 {{ palette.purple_light }}
color14 {{ palette.teal_light }}
color15 {{ palette.white }}
