// Generated by zen0x — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color bg:       "{{ semantic.bg }}"
    readonly property color panel:    "{{ semantic.panel }}"
    readonly property color panelAlt: "{{ semantic.panel_alt }}"
    readonly property color fg:       "{{ semantic.fg }}"
    readonly property color muted:    "{{ semantic.muted }}"
    readonly property color accent:   "{{ semantic.accent }}"
    readonly property color danger:   "{{ semantic.danger }}"
}
