package.loaded["zen0x.colors"] = nil
local ok, colors = pcall(require, "zen0x.colors")
if not ok then
  vim.notify("zen0x: run zen0x-apply-theme first", vim.log.levels.WARN)
  return
end

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "zen0x"

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hl("Normal",           { bg = colors.bg,      fg = colors.fg })
hl("NormalNC",         { bg = colors.bg,      fg = colors.fg })
hl("NormalFloat",      { bg = colors.panel,   fg = colors.fg })
hl("FloatBorder",      { fg = colors.border })
hl("WinSeparator",     { fg = colors.border })
hl("VertSplit",        { fg = colors.border })
hl("CursorLine",       { bg = colors.surface })
hl("CursorLineNr",     { fg = colors.subtle,  bold = true })
hl("ColorColumn",      { bg = colors.surface })
hl("LineNr",           { fg = colors.muted })
hl("SignColumn",       { bg = colors.bg })
hl("StatusLine",       { bg = colors.panel,   fg = colors.fg })
hl("StatusLineNC",     { bg = colors.panel,   fg = colors.muted })
hl("TabLine",          { bg = colors.panel,   fg = colors.muted })
hl("TabLineSel",       { bg = colors.bg,      fg = colors.fg,    bold = true })
hl("TabLineFill",      { bg = colors.panel })
hl("Visual",           { bg = colors.elevated })
hl("VisualNOS",        { bg = colors.elevated })
hl("Search",           { bg = colors.accent,  fg = colors.bg })
hl("IncSearch",        { bg = colors.accent,  fg = colors.bg })
hl("CurSearch",        { bg = colors.accent,  fg = colors.bg })
hl("MatchParen",       { bg = colors.elevated, bold = true })
hl("Pmenu",            { bg = colors.panel,   fg = colors.fg })
hl("PmenuSel",         { bg = colors.elevated, fg = colors.fg })
hl("PmenuSbar",        { bg = colors.surface })
hl("PmenuThumb",       { bg = colors.accent })
hl("NonText",          { fg = colors.muted })
hl("SpecialKey",       { fg = colors.muted })
hl("Whitespace",       { fg = colors.subtle })
hl("EndOfBuffer",      { fg = colors.subtle })
hl("Folded",           { bg = colors.surface, fg = colors.muted })
hl("FoldColumn",       { bg = colors.bg,      fg = colors.muted })
hl("Title",            { fg = colors.accent,  bold = true })
hl("Question",         { fg = colors.accent })
hl("MoreMsg",          { fg = colors.success })
hl("WarningMsg",       { fg = colors.warning })
hl("ErrorMsg",         { fg = colors.danger })
hl("ModeMsg",          { fg = colors.fg })
hl("MsgArea",          { fg = colors.fg })
hl("Conceal",          { fg = colors.muted })
hl("SpellBad",         { sp = colors.danger,   undercurl = true })
hl("SpellCap",         { sp = colors.warning,  undercurl = true })
hl("SpellRare",        { sp = colors.accent,   undercurl = true })
hl("SpellLocal",       { sp = colors.success,  undercurl = true })

-- Syntax
hl("Comment",          { fg = colors.muted,    italic = true })
hl("String",           { fg = colors.success })
hl("Character",        { fg = colors.success })
hl("Number",           { fg = colors.orange_light })
hl("Float",            { fg = colors.orange_light })
hl("Boolean",          { fg = colors.red_dark })
hl("Constant",         { fg = colors.red_light })
hl("Identifier",       { fg = colors.fg })
hl("Function",         { fg = colors.accent_alt })
hl("Statement",        { fg = colors.accent })
hl("Keyword",          { fg = colors.accent })
hl("Conditional",      { fg = colors.accent })
hl("Repeat",           { fg = colors.accent })
hl("Label",            { fg = colors.accent })
hl("Operator",         { fg = colors.fg })
hl("Exception",        { fg = colors.danger })
hl("PreProc",          { fg = colors.warning })
hl("Include",          { fg = colors.accent })
hl("Define",           { fg = colors.accent })
hl("Macro",            { fg = colors.accent })
hl("PreCondit",        { fg = colors.accent })
hl("Type",             { fg = colors.warning })
hl("StorageClass",     { fg = colors.accent })
hl("Structure",        { fg = colors.warning })
hl("Typedef",          { fg = colors.warning })
hl("Special",          { fg = colors.accent_alt })
hl("SpecialChar",      { fg = colors.accent_alt })
hl("Tag",              { fg = colors.accent })
hl("Delimiter",        { fg = colors.fg })
hl("SpecialComment",   { fg = colors.muted,    italic = true })
hl("Debug",            { fg = colors.danger })
hl("Underlined",       { underline = true })
hl("Ignore",           { fg = colors.muted })
hl("Error",            { fg = colors.danger })
hl("Todo",             { fg = colors.warning,  bold = true })

-- Diagnostics
hl("DiagnosticError",             { fg = colors.danger })
hl("DiagnosticWarn",              { fg = colors.warning })
hl("DiagnosticInfo",              { fg = colors.accent })
hl("DiagnosticHint",              { fg = colors.muted })
hl("DiagnosticOk",                { fg = colors.success })
hl("DiagnosticUnderlineError",    { sp = colors.danger,   undercurl = true })
hl("DiagnosticUnderlineWarn",     { sp = colors.warning,  undercurl = true })
hl("DiagnosticUnderlineInfo",     { sp = colors.accent,   undercurl = true })
hl("DiagnosticUnderlineHint",     { sp = colors.muted,    undercurl = true })
hl("DiagnosticVirtualTextError",  { fg = colors.danger,   bg = colors.bg })
hl("DiagnosticVirtualTextWarn",   { fg = colors.warning,  bg = colors.bg })
hl("DiagnosticVirtualTextInfo",   { fg = colors.accent,   bg = colors.bg })
hl("DiagnosticVirtualTextHint",   { fg = colors.muted,    bg = colors.bg })

-- Treesitter
hl("@comment",               { link = "Comment" })
hl("@string",                { link = "String" })
hl("@string.escape",         { fg = colors.accent_alt })
hl("@number",                { link = "Number" })
hl("@float",                 { link = "Float" })
hl("@boolean",               { link = "Boolean" })
hl("@constant",              { link = "Constant" })
hl("@constant.builtin",      { fg = colors.red_light })
hl("@variable",              { fg = colors.fg })
hl("@variable.builtin",      { fg = colors.accent })
hl("@parameter",             { fg = colors.fg })
hl("@field",                 { fg = colors.fg })
hl("@property",              { fg = colors.fg })
hl("@function",              { link = "Function" })
hl("@function.builtin",      { fg = colors.accent_alt })
hl("@function.call",         { fg = colors.accent_alt })
hl("@method",                { fg = colors.accent_alt })
hl("@method.call",           { fg = colors.accent_alt })
hl("@constructor",           { fg = colors.warning })
hl("@keyword",               { link = "Keyword" })
hl("@keyword.function",      { fg = colors.accent })
hl("@keyword.return",        { fg = colors.accent })
hl("@keyword.operator",      { fg = colors.accent })
hl("@conditional",           { link = "Conditional" })
hl("@repeat",                { link = "Repeat" })
hl("@type",                  { link = "Type" })
hl("@type.builtin",          { fg = colors.warning })
hl("@type.definition",       { fg = colors.warning })
hl("@namespace",             { fg = colors.fg })
hl("@operator",              { link = "Operator" })
hl("@punctuation",           { fg = colors.fg })
hl("@punctuation.bracket",   { fg = colors.fg })
hl("@punctuation.delimiter", { fg = colors.fg })
hl("@tag",                   { fg = colors.accent })
hl("@tag.attribute",         { fg = colors.warning })
hl("@tag.delimiter",         { fg = colors.muted })
hl("@text.uri",              { fg = colors.accent,   underline = true })
hl("@text.reference",        { fg = colors.accent })
hl("@text.strong",           { bold = true })
hl("@text.emphasis",         { italic = true })
hl("@text.title",            { fg = colors.accent,   bold = true })
hl("@text.literal",          { fg = colors.success })

-- Git signs (gitsigns.nvim)
hl("GitSignsAdd",            { fg = colors.success })
hl("GitSignsChange",         { fg = colors.warning })
hl("GitSignsDelete",         { fg = colors.danger })

-- Diff
hl("DiffAdd",                { bg = colors.bg,      fg = colors.success })
hl("DiffChange",             { bg = colors.bg,      fg = colors.warning })
hl("DiffDelete",             { bg = colors.bg,      fg = colors.danger })
hl("DiffText",               { bg = colors.elevated })
