[config]

[templates.kitty]
input_path  = '~/dotfiles/templates/kitty-colors.conf'
output_path = '~/dotfiles/kitty/colors.conf'
post_hook   = 'pkill -SIGUSR1 kitty || true'

[templates.hyprland]
input_path  = '~/dotfiles/templates/hyprland-colors.conf'
output_path = '~/dotfiles/hypr/colors.conf'
post_hook   = 'hyprctl reload || true'

[templates.quickshell]
input_path  = '~/dotfiles/templates/Colors.qml'
output_path = '~/dotfiles/quickshell/Colors.qml'

[templates.gtk4]
input_path  = '~/dotfiles/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.fastfetch]
input_path  = '~/dotfiles/templates/fastfetch-config.jsonc'
output_path = '~/dotfiles/fastfetch/config.jsonc'

[templates.vscode]
input_path  = '~/dotfiles/templates/vscode-colors.json'
output_path = '~/.config/Code/User/matugen-colors.json'
