{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
    "bg":         "{{ semantic.bg }}",
    "surface":    "{{ semantic.surface }}",
    "panel":      "{{ semantic.panel }}",
    "panelAlt":   "{{ semantic.panel_alt }}",
    "elevated":   "{{ semantic.elevated }}",
    "border":     "{{ semantic.border }}",
    "borderActive": "{{ semantic.accent }}",
    "fg":         "{{ semantic.fg }}",
    "muted":      "{{ semantic.muted }}",
    "subtle":     "{{ semantic.subtle }}",
    "accent":     "{{ semantic.accent }}",
    "accentAlt":  "{{ semantic.accent_alt }}",
    "danger":     "{{ semantic.danger }}",
    "success":    "{{ semantic.success }}",
    "warning":    "{{ semantic.warning }}",
    "link":       "{{ semantic.link }}",
    "red":        "{{ palette.red_light }}",
    "redDark":    "{{ palette.red_dark }}",
    "pink":       "{{ palette.pink_light }}",
    "purple":     "{{ palette.purple_light }}",
    "blue":       "{{ palette.blue_light }}",
    "teal":       "{{ palette.teal_light }}",
    "green":      "{{ palette.green_light }}",
    "yellow":     "{{ palette.yellow_light }}",
    "orange":     "{{ palette.orange_light }}",
    "grey050":    "{{ palette.grey_050 }}",
    "grey200":    "{{ palette.grey_200 }}",
    "grey300":    "{{ palette.grey_300 }}",
    "grey350":    "{{ palette.grey_350 }}",
    "grey400":    "{{ palette.grey_400 }}",
    "grey500":    "{{ palette.grey_500 }}",
    "grey600":    "{{ palette.grey_600 }}",
    "white":      "{{ palette.white }}",
    "black":      "{{ palette.black }}"
  },
  "theme": {
    "primary":    "accent",
    "secondary":  "teal",
    "accent":     "accentAlt",
    "error":      "danger",
    "warning":    "warning",
    "success":    "success",
    "info":       "blue",

    "text":       "fg",
    "textMuted":  "muted",

    "background":        "bg",
    "backgroundPanel":   "panel",
    "backgroundElement": "elevated",

    "border":       "border",
    "borderActive": "borderActive",
    "borderSubtle": "subtle",

    "diffAdded":               "green",
    "diffRemoved":             "red",
    "diffContext":             "fg",
    "diffHunkHeader":          "accent",
    "diffHighlightAdded":      "green",
    "diffHighlightRemoved":    "red",
    "diffAddedBg":             "grey400",
    "diffRemovedBg":           "grey400",
    "diffContextBg":           "bg",
    "diffLineNumber":          "muted",
    "diffAddedLineNumberBg":   "grey350",
    "diffRemovedLineNumberBg": "grey350",

    "markdownText":            "fg",
    "markdownHeading":         "accent",
    "markdownLink":            "link",
    "markdownCode":            "teal",
    "markdownBlockQuote":      "muted",
    "markdownEmph":            "yellow",
    "markdownStrong":          "orange",
    "markdownHorizontalRule":  "border",
    "markdownListItem":        "fg",
    "markdownListEnumeration": "accent",
    "markdownImage":           "accent",
    "markdownImageText":       "muted",
    "markdownCodeBlock":       "teal",

    "syntaxComment":     "muted",
    "syntaxKeyword":     "purple",
    "syntaxFunction":    "blue",
    "syntaxVariable":    "fg",
    "syntaxString":      "green",
    "syntaxNumber":      "orange",
    "syntaxType":        "yellow",
    "syntaxOperator":    "teal",
    "syntaxPunctuation": "subtle"
  }
}
