// Generated by zen0x — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color bg:       "#2B3339"
    readonly property color panel:    "#2B3339"
    readonly property color panelAlt: "#323C41"
    readonly property color fg:       "#D3C6AA"
    readonly property color muted:    "#9DA9A0"
    readonly property color accent:   "#7FBBB3"
    readonly property color danger:   "#E67E80"
}
