// Generated by matugen — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color bg:       "#101510"
    readonly property color panel:    "#101510"
    readonly property color panelAlt: "#414941"
    readonly property color fg:       "#dfe4dc"
    readonly property color muted:    "#c1c9bf"
    readonly property color accent:   "#97d5a5"
    readonly property color danger:   "#ffb4ab"
}
