# Main Hyprland entry point.
# Edit the focused files in modules/ for day-to-day changes.

source = /home/aman/.config/hypr/modules/00-monitors.conf
source = /home/aman/.config/hypr/modules/01-programs.conf
source = /home/aman/.config/hypr/modules/10-autostart.conf
source = /home/aman/.config/hypr/modules/20-environment.conf
source = /home/aman/.config/hypr/modules/30-permissions.conf
source = /home/aman/.config/hypr/modules/40-look-and-feel.conf
source = /home/aman/.config/hypr/modules/50-layouts.conf
source = /home/aman/.config/hypr/modules/60-input.conf
source = /home/aman/.config/hypr/modules/70-binds.conf
source = /home/aman/.config/hypr/modules/80-rules.conf
