###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty
$fileManager = nautilus
$browser = zen-browser
$menu = rofi -show drun -theme ~/.config/rofi/launcher.rasi
