hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm app -- noctalia")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- easyeffects --gapplication-service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
