#################
### AUTOSTART ###
#################

exec-once = uwsm app -- waybar
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- swayosd-server
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
