#################
### AUTOSTART ###
#################

exec-once = uwsm app -- waybar
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- swayosd-server --config /home/aman/.config/swayosd/config.toml
exec-once = uwsm app -- openrgb -p red

# Clipboard history daemon
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

