#################
### AUTOSTART ###
#################

exec-once = uwsm app -- waybar
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- swayosd-server --config /home/aman/.config/swayosd/config.toml

