#####################
### LOOK AND FEEL ###
#####################

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out =15
    gaps_workspaces = 28

    border_size = 1
    col.active_border = rgb(89b4fa)
    col.inactive_border = rgba(313244aa)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 14
    rounding_power = 2.6

    active_opacity = 0.98
    inactive_opacity = 0.90
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.12
    dim_special = 0.18

    shadow {
        enabled = true
        range = 24
        render_power = 4
        color = rgba(11111bcc)
        color_inactive = rgba(00000066)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        ignore_opacity = true
        new_optimizations = true
        vibrancy = 0.22
        vibrancy_darkness = 0.35
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = false

    bezier = easeOut,       0.25, 1,    0.5,  1
    bezier = easeIn,        0.5,  0,    0.75, 0
    bezier = easeInOut,     0.45, 0,    0.55, 1
    bezier = quickFade,     0.3,  0,    0.7,  1

    animation = global,        1,     12,    easeOut
    animation = border,        0,     1,     easeOut
    animation = windows,       1,     12,    easeOut
    animation = windowsIn,     1,     12,    easeOut
    animation = windowsOut,    1,     11,    easeIn
    animation = fadeIn,        1,     10,    quickFade
    animation = fadeOut,       1,     10,    quickFade
    animation = fade,          1,     10,    quickFade
    animation = layers,        0,     1,     easeOut
    animation = layersIn,      0,     1,     easeOut,      fade
    animation = layersOut,     0,     1,     easeIn,       fade
    animation = fadeLayersIn,  1,     10,    quickFade
    animation = fadeLayersOut, 1,     10,    quickFade
    animation = workspaces,    1,     11,    easeOut,      slide
    animation = workspacesIn,  1,     11,    easeOut,      slide
    animation = workspacesOut, 1,     10,    easeIn,       slide
    animation = zoomFactor,    0,     1,     easeOut
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    focus_on_activate = true
    vfr = true
    vrr = 1
}
