local colors = require("colors")

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        gaps_workspaces = 10,
        border_size = 1,
        ["col.active_border"] = colors.active_border,
        ["col.inactive_border"] = colors.inactive_border,
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 14,
        rounding_power = 2.6,
        active_opacity = 0.85,
        inactive_opacity = 0.75,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.12,
        dim_special = 0.18,
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            offset = { 0, 4 },
            color = colors.shadow_color,
            color_inactive = colors.shadow_inactive_color,
        },
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            ignore_opacity = true,
            new_optimizations = true,
            vibrancy = 0.22,
            vibrancy_darkness = 0.35,
        },
    },
    animations = {
        enabled = true,
        bezier = {
            { name = "easeOutExpo", args = { 0.16, 1, 0.3, 1 } },
            { name = "easeOutBack", args = { 0.34, 1.56, 0.64, 1 } },
            { name = "easeInCubic", args = { 0.32, 0, 0.67, 0 } },
            { name = "easeInOut", args = { 0.65, 0, 0.35, 1 } },
            { name = "easeOut", args = { 0.25, 1, 0.5, 1 } },
            { name = "easeIn", args = { 0.5, 0, 0.75, 0 } },
            { name = "spring", args = { 0.16, 1.15, 0.28, 1 } },
        },
        animation = {
            { name = "windows", enabled = true, speed = 3, curve = "easeOut", style = "popin 80%" },
            { name = "windowsIn", enabled = true, speed = 3, curve = "easeOut", style = "popin 80%" },
            { name = "windowsOut", enabled = true, speed = 2, curve = "easeOut", style = "popin 90%" },
            { name = "windowsMove", enabled = true, speed = 2, curve = "easeOut", style = "slide" },
            { name = "border", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fade", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fadeIn", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fadeOut", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fadeSwitch", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fadeDim", enabled = true, speed = 2, curve = "easeOut" },
            { name = "fadeLayers", enabled = true, speed = 2, curve = "easeOut" },
            { name = "layers", enabled = true, speed = 2, curve = "easeOut", style = "fade" },
            { name = "layersIn", enabled = true, speed = 2, curve = "easeOut", style = "fade" },
            { name = "layersOut", enabled = true, speed = 1, curve = "easeOut", style = "fade" },
            { name = "workspaces", enabled = true, speed = 3, curve = "easeOut", style = "slidefade 15%" },
            { name = "workspacesIn", enabled = true, speed = 3, curve = "easeOut", style = "slidefade 15%" },
            { name = "workspacesOut", enabled = true, speed = 2, curve = "easeOut", style = "slidefade 15%" },
            { name = "specialWorkspace", enabled = true, speed = 3, curve = "easeOut", style = "slidevert" },
        },
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        focus_on_activate = true,
        vrr = 1,
    },
})
