#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/colors.conf

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 10
    gaps_out = 20
    gaps_workspaces = 10

    border_size = 1
    col.active_border = $active_border
    col.inactive_border = $inactive_border

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 14
    rounding_power = 2.6

    active_opacity = 0.85
    inactive_opacity = 0.75
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.12
    dim_special = 0.18

    shadow {
        enabled = true
        range = 20
        render_power = 3
        offset = 0 4
        color = $shadow_color
        color_inactive = $shadow_inactive_color
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        ignore_opacity = true
        new_optimizations = true
        vibrancy = 0.22
        vibrancy_darkness = 0.35
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = true

    bezier = easeOutExpo,   0.16, 1,    0.3,  1
    bezier = easeOutBack,   0.34, 1.56, 0.64, 1
    bezier = easeInCubic,   0.32, 0,    0.67, 0
    bezier = easeInOut,     0.65, 0,    0.35, 1
    bezier = easeOut,       0.25, 1,    0.5,  1
    bezier = easeIn,        0.5,  0,    0.75, 0
    bezier = spring,        0.16, 1.15, 0.28, 1

    animation = windows,        1,  3,  easeOut,      popin 80%
    animation = windowsIn,      1,  3,  easeOut,      popin 80%
    animation = windowsOut,     1,  2,  easeOut,      popin 90%
    animation = windowsMove,    1,  2,  easeOut,      slide

    animation = border,         1,  2,  easeOut

    animation = fade,           1,  2,  easeOut
    animation = fadeIn,         1,  2,  easeOut
    animation = fadeOut,        1,  2,  easeOut
    animation = fadeSwitch,     1,  2,  easeOut
    animation = fadeDim,        1,  2,  easeOut
    animation = fadeLayers,     1,  2,  easeOut

    animation = layers,         1,  2,  easeOut,      fade
    animation = layersIn,       1,  2,  easeOut,      fade
    animation = layersOut,      1,  1,  easeOut,      fade

    animation = workspaces,     1,  3,  easeOut,      slidefade 15%
    animation = workspacesIn,   1,  3,  easeOut,      slidefade 15%
    animation = workspacesOut,  1,  2,  easeOut,      slidefade 15%

    animation = specialWorkspace, 1, 3, easeOut, slidevert
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    focus_on_activate = true
    vfr = true
    vrr = 1
}
