local function set_keyword(key, value)
    hl.exec_cmd(string.format("hyprctl keyword %s %s", key, value))
end

hl.on("hyprland.start", function()
    set_keyword("plugin:scrolloverview:gesture_distance", "300")
    set_keyword("plugin:scrolloverview:scale", "0.5")
    set_keyword("plugin:scrolloverview:workspace_gap", "100")
    set_keyword("plugin:scrolloverview:wallpaper", "0")
    set_keyword("plugin:scrolloverview:blur", "true")
    set_keyword("plugin:scrolloverview:shadow:enabled", "true")
    set_keyword("plugin:scrolloverview:shadow:range", "20")
    set_keyword("plugin:scrolloverview:shadow:render_power", "3")
    set_keyword("plugin:scrolloverview:shadow:ignore_window", "false")
end)
