local programs = require("modules/01-programs")

local main_mod = "SUPER"

local function bind_workspace(key, workspace)
    hl.bind(main_mod .. " + " .. key, function()
        hl.exec_cmd("hyprctl dispatch workspace " .. workspace)
    end)
    hl.bind(main_mod .. " + SHIFT + " .. key, function()
        hl.exec_cmd("hyprctl dispatch movetoworkspace " .. workspace)
    end)
end

hl.bind(main_mod .. " + RETURN", hl.dsp.exec_cmd(programs.terminal))
hl.bind(main_mod .. " + W", function()
    hl.exec_cmd("hyprctl dispatch killactive")
end)
hl.bind(main_mod .. " + SHIFT + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || uwsm stop"))
hl.bind(main_mod .. " + E", hl.dsp.exec_cmd(programs.file_manager))
hl.bind(main_mod .. " + B", hl.dsp.exec_cmd(programs.browser))
hl.bind(main_mod .. " + SHIFT + F", function()
    hl.exec_cmd("hyprctl dispatch fullscreen 0")
end)

hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(programs.menu))
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("code"))
hl.bind("SUPER + SHIFT + ESCAPE", hl.dsp.exec_cmd("zen0x-powermenu"))
hl.bind("SUPER + SHIFT + SPACE", hl.dsp.exec_cmd("zen0x-theme-menu"))
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("zen0x-theme-reload"))

hl.bind(main_mod .. " + left", function() hl.exec_cmd("hyprctl dispatch movefocus l") end)
hl.bind(main_mod .. " + right", function() hl.exec_cmd("hyprctl dispatch movefocus r") end)
hl.bind(main_mod .. " + up", function() hl.exec_cmd("hyprctl dispatch movefocus u") end)
hl.bind(main_mod .. " + down", function() hl.exec_cmd("hyprctl dispatch movefocus d") end)
hl.bind(main_mod .. " + H", function() hl.exec_cmd("hyprctl dispatch movefocus l") end)
hl.bind(main_mod .. " + L", function() hl.exec_cmd("hyprctl dispatch movefocus r") end)
hl.bind(main_mod .. " + K", function() hl.exec_cmd("hyprctl dispatch movefocus u") end)
hl.bind(main_mod .. " + J", function() hl.exec_cmd("hyprctl dispatch movefocus d") end)

hl.bind(main_mod .. " + SHIFT + H", function() hl.exec_cmd("hyprctl dispatch swapwindow l") end)
hl.bind(main_mod .. " + SHIFT + L", function() hl.exec_cmd("hyprctl dispatch swapwindow r") end)
hl.bind(main_mod .. " + SHIFT + K", function() hl.exec_cmd("hyprctl dispatch swapwindow u") end)
hl.bind(main_mod .. " + SHIFT + J", function() hl.exec_cmd("hyprctl dispatch swapwindow d") end)

bind_workspace("1", 1)
bind_workspace("2", 2)
bind_workspace("3", 3)
bind_workspace("4", 4)
bind_workspace("5", 5)
bind_workspace("6", 6)
bind_workspace("7", 7)
bind_workspace("8", 8)
bind_workspace("9", 9)
bind_workspace("0", 10)

hl.bind(main_mod .. " + V", function() hl.exec_cmd("hyprctl dispatch togglefloating") end)
hl.bind(main_mod .. " + P", function() hl.exec_cmd("hyprctl dispatch pseudo") end)
hl.bind(main_mod .. " + G", function() hl.exec_cmd("hyprctl dispatch togglegroup") end)
hl.bind(main_mod .. " + TAB", function() hl.exec_cmd("hyprctl dispatch changegroupactive f") end)

hl.bind(main_mod .. " + CTRL + right", function() hl.exec_cmd("hyprctl dispatch resizeactive 30 0") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + left", function() hl.exec_cmd("hyprctl dispatch resizeactive -30 0") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + up", function() hl.exec_cmd("hyprctl dispatch resizeactive 0 -30") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + down", function() hl.exec_cmd("hyprctl dispatch resizeactive 0 30") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + L", function() hl.exec_cmd("hyprctl dispatch resizeactive 30 0") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + H", function() hl.exec_cmd("hyprctl dispatch resizeactive -30 0") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + K", function() hl.exec_cmd("hyprctl dispatch resizeactive 0 -30") end, { repeating = true })
hl.bind(main_mod .. " + CTRL + J", function() hl.exec_cmd("hyprctl dispatch resizeactive 0 30") end, { repeating = true })

hl.bind(main_mod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region | satty --filename -"))
hl.bind(main_mod .. " + mouse_down", function() hl.exec_cmd("hyprctl dispatch workspace e+1") end)
hl.bind(main_mod .. " + mouse_up", function() hl.exec_cmd("hyprctl dispatch workspace e-1") end)

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true, repeating = true })
hl.bind("Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("SUPER + C", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -theme ~/.config/rofi/launcher.rasi | cliphist decode | wl-copy"))
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -a"))
