##############################
### WINDOWS AND WORKSPACES ###
##############################

layerrule {
    name = blur-quickshell
    match:namespace = quickshell

    blur = true
    ignore_alpha = 0.05
}

layerrule {
    name = blur-launcher
    match:namespace = launcher

    blur = true
    ignore_alpha = 0.05
}

layerrule {
    name = blur-notifications
    match:namespace = notifications

    blur = true
    ignore_alpha = 0.05
}

layerrule {
    name = blur-controlcenter
    match:namespace = controlcenter

    blur = true
    ignore_alpha = 0.05
}

layerrule {
    name = blur-waybar
    match:namespace = waybar

    blur = true
    ignore_alpha = 0.05
}

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = polished-common-dialogs
    match:title = ^(Open|Save|Save As|Choose|Select|File Upload)(.*)$

    float = true
    center = true
    size = 60% 65%
    opacity = 0.98 0.94
}

windowrule {
    name = polished-picture-in-picture
    match:title = ^(Picture-in-Picture|Picture in picture)$

    float = true
    pin = true
    size = 30% 30%
    move = 69% 64%
    opacity = 0.96 0.90
}

windowrule {
    name = airy-floating-windows
    match:float = true

    rounding = 18
    border_size = 3
    opacity = 0.97 0.92
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = float-steam
    match:class = ^(steam|Steam)$
    match:fullscreen = false

    float = true
    center = true
    size = 900 600
}

windowrule {
    name = float-files
    match:class = ^(org.gnome.Nautilus)$
    match:fullscreen = false

    float = true
    center = true
    size = 900 600
}

windowrule {
    name = float-unityhub
    match:class = ^(unityhub)$
    match:fullscreen = false

    float = true
    center = true
    size = 900 600
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
