/* Generated by zen0x — do not edit by hand */
@define-color bg       {{ semantic.bg }};
@define-color panel    {{ semantic.panel }};
@define-color panelAlt {{ semantic.panel_alt }};
@define-color fg       {{ semantic.fg }};
@define-color muted    {{ semantic.muted }};
@define-color accent   {{ semantic.accent }};
@define-color danger   {{ semantic.danger }};
