// Generated by matugen — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color bg:       "{{ colors.background.default.hex }}"
    readonly property color panel:    "{{ colors.surface.default.hex }}"
    readonly property color panelAlt: "{{ colors.surface_variant.default.hex }}"
    readonly property color fg:       "{{ colors.on_background.default.hex }}"
    readonly property color muted:    "{{ colors.on_surface_variant.default.hex }}"
    readonly property color accent:   "{{ colors.primary.default.hex }}"
    readonly property color danger:   "{{ colors.error.default.hex }}"
}
