$active_border = rgb({{ colors.primary.default.hex_stripped }})
$inactive_border = rgba({{ colors.outline.default.hex_stripped }}aa)
$shadow_color = rgba({{ colors.background.default.hex_stripped }}cc)
$shadow_inactive_color = rgba({{ colors.background.default.hex_stripped }}66)
