foreground {{ colors.on_background.default.hex }}
background {{ colors.background.default.hex }}
selection_foreground {{ colors.background.default.hex }}
selection_background {{ colors.primary.default.hex }}
url_color {{ colors.primary.default.hex }}

color0  {{ colors.surface.default.hex }}
color1  {{ colors.error.default.hex }}
color2  {{ colors.tertiary.default.hex }}
color3  {{ colors.secondary.default.hex }}
color4  {{ colors.primary.default.hex }}
color5  {{ colors.on_primary_container.default.hex }}
color6  {{ colors.primary_container.default.hex }}
color7  {{ colors.on_surface_variant.default.hex }}
color8  {{ colors.outline.default.hex }}
color9  {{ colors.error_container.default.hex }}
color10 {{ colors.tertiary_container.default.hex }}
color11 {{ colors.secondary_container.default.hex }}
color12 {{ colors.primary_container.default.hex }}
color13 {{ colors.on_tertiary.default.hex }}
color14 {{ colors.on_secondary_container.default.hex }}
color15 {{ colors.on_background.default.hex }}

cursor            {{ colors.on_background.default.hex }}
cursor_text_color {{ colors.background.default.hex }}
