# Generated by zen0x — do not edit by hand

[server]
# Custom stylesheet path (generated by zen0x theme engine)
style = "/home/aman/.config/swayosd/style.css"

# OSD vertical position (0.0 = top, 0.5 = center, 1.0 = bottom)
top_margin = 0.85

# Maximum volume percentage (allows over-amplification)
max_volume = 150

# Minimum brightness percentage
min_brightness = 5

# Show percentage text next to progress bar
show_percentage = true

# Media player OSD format
playerctl_format = "{artist} - {title}"

# Auto-display OSD for keyboard backlight changes
keyboard_backlight = true

[client]
# Client-specific configuration (currently empty)
