/* Generated by zen0x — do not edit by hand */
:root {
  color-scheme: {{ meta.variant }};
  --zen0x-bg: {{ semantic.bg }};
  --zen0x-surface: {{ semantic.surface }};
  --zen0x-panel: {{ semantic.panel }};
  --zen0x-panel-alt: {{ semantic.panel_alt }};
  --zen0x-elevated: {{ semantic.elevated }};
  --zen0x-border: {{ semantic.border }};
  --zen0x-fg: {{ semantic.fg }};
  --zen0x-muted: {{ semantic.muted }};
  --zen0x-accent: {{ semantic.accent }};
  --zen0x-link: {{ semantic.link }};
  --zen0x-danger: {{ semantic.danger }};
  --zen0x-success: {{ semantic.success }};
  --zen0x-warning: {{ semantic.warning }};
  --zen0x-selection: {{ palette.grey_500 }};
}

html,
body {
  background: var(--zen0x-bg) !important;
  color: var(--zen0x-fg) !important;
}

body,
[role="main"],
[role="complementary"],
[role="navigation"],
[role="dialog"],
[role="menu"],
[class*="app"],
[class*="pane"],
[class*="panel"],
[class*="drawer"] {
  scrollbar-color: var(--zen0x-border) transparent;
}

a,
[role="link"] {
  color: var(--zen0x-link) !important;
}

button,
input,
textarea,
select,
progress {
  accent-color: var(--zen0x-accent) !important;
}

button:focus-visible,
input:focus-visible,
textarea:focus-visible,
select:focus-visible,
[role="button"]:focus-visible,
[tabindex]:focus-visible {
  outline: 2px solid var(--zen0x-accent) !important;
  outline-offset: 2px;
}

[role="dialog"],
[role="menu"],
[role="listbox"],
[class*="menu"],
[class*="popover"],
[class*="modal"],
[class*="surface"] {
  background: var(--zen0x-elevated) !important;
  border-color: var(--zen0x-border) !important;
  color: var(--zen0x-fg) !important;
}

::selection {
  background: var(--zen0x-selection) !important;
  color: var(--zen0x-fg) !important;
}

::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

::-webkit-scrollbar-thumb {
  background: var(--zen0x-border);
  border: 2px solid transparent;
  border-radius: 999px;
  background-clip: padding-box;
}

::-webkit-scrollbar-thumb:hover {
  background: var(--zen0x-accent);
  background-clip: padding-box;
}
